############################
########## <Post> ##########
############################

### Create Post
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "First Post",
  "body": "This is my first post",
  "senderID": "64bfa12c9e1a4a00123abcd1"
}

### Get All Posts
GET http://localhost:3000/post

### Get Post By ID
GET http://localhost:3000/post/697ca050ea3dafa7b8f902af

### Get Posts By Sender
GET http://localhost:3000/post?senderID=64bfa12c9e1a4a00123abcd1

### Update Post
PUT http://localhost:3000/post/697ca050ea3dafa7b8f902af
Content-Type: application/json

{
  "title": "Updated Post Title",
  "body": "Updated content"
}

### Delete Post
DELETE http://localhost:3000/post/697ca050ea3dafa7b8f902af


###############################
########## <Comment> ##########
###############################

### Create Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
  "postID": "697ca050ea3dafa7b8f902af",
  "userID": "64bfa12c9e1a4a00123abcd1",
  "content": "Nice Post!!!"
}

### Get All Comments
GET http://localhost:3000/comment

### Get Comment By ID
GET http://localhost:3000/comment/697ca099ea3dafa7b8f902bd

### Get Comments By Post
GET http://localhost:3000/comment?postID=697ca050ea3dafa7b8f902af

### Update Comment
PUT http://localhost:3000/comment/697ca099ea3dafa7b8f902bd
Content-Type: application/json

{
  "content": "Edited comment content"
}

### Delete Comment
DELETE http://localhost:3000/comment/697ca099ea3dafa7b8f902bd